### ISSUE TITLE
undefined method 'new' for Cossack:Module

### ISSUE THREAD

**Issue by icyleaf** [greyblake/crystal-cossack#1]
crystal version: `Crystal 0.17.4 (2016-05-26)`

shards.yml:

```yaml
dependencies:
  cossack:
    github: greyblake/crystal-cossack
```

cr file:

```crystal
require "cossack"
cossack = Cossack.new
```
